[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DroneSurveillance = "63556450-714a-11e9-08e1-e368b701e279"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NativeSARSOP = "a07c76ea-660d-4c9a-8028-2e6dbd212cb8"
POMDPGifs = "7f35509c-0cb9-11e9-0708-2928828cdbb7"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RockSample = "de008ff0-c357-11e8-3329-7fe746fe836e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
